import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {readJSON,parseProject,parseSnippet,analyzeProject,parseWhen,evaluateWhen,serializeWhen,validateKey} from '../src/core.mjs';
import {makeArtifacts,createZip} from '../src/exports.mjs';
const sample=()=>JSON.parse(fs.readFileSync('fixtures/twelve-contexts.json','utf8'));
const chosen={'ctrl+alt+k':['s1:r2','s2:r1','s1:r1']};
const project=(rules,model={},platform='linux')=>({version:1,platform,sources:[{name:'Unit source',rules}],model});
const bools={a:{type:'boolean',values:[true,false,null]},b:{type:'boolean',values:[true,false,null]}};
const model={...bools,lang:{type:'string',values:['python','javascript','false','hello world',null]}};
const rule=(when,command='command',args)=>({key:'ctrl+k',command,...(when===undefined?{}:{when}),...(args===undefined?{}:{args})});
test('fixture default preserves imported bottom-to-top winner across 12 contexts',()=>{const r=analyzeProject(sample());assert.equal(r.stats.contextCount,12);assert.equal(r.stats.changedCount,0);const row=r.scenarios.find(x=>x.context['whenfold.focus']&&x.context['whenfold.selection']&&x.context['whenfold.lang']==='python');assert.equal(row.before.command,'demo.selection');assert.deepEqual(row.before,row.after);});
test('explicit Python priority changes exactly one context and retains args',()=>{const r=analyzeProject(sample(),chosen);assert.equal(r.delta.length,1);assert.deepEqual(r.delta[0].context,{'whenfold.focus':true,'whenfold.selection':true,'whenfold.lang':'python'});assert.equal(r.delta[0].before.command,'demo.selection');assert.equal(r.delta[0].after.command,'demo.python');assert.deepEqual(JSON.parse(JSON.stringify(r.delta[0].after.args)),{kind:'python',nested:{preserve:['a',false,null]}});assert.ok(r.scenarios.every(s=>s.matchedExportIds.length<=1));});
test('opposite language conditions share key but are disjoint',()=>{const r=analyzeProject(project([rule('lang == python','python'),rule('lang == javascript','js')],model));assert.equal(r.overlaps.length,0);assert.equal(r.delta.length,0);});
test('shadowed and unconditional rules are retained with false guard',()=>{const r=analyzeProject(project([rule('a','low'),rule(undefined,'high')],bools));assert.equal(r.stats.shadowedCount,1);assert.equal(r.exported[0].when,'false');assert.equal(r.scenarios.every(s=>s.after.command==='high'),true);});
test('same command different args counts as behavior change',()=>{const p=project([rule('a','same',{x:1}),rule('a','same',{x:2})],bools);assert.equal(analyzeProject(p,{'ctrl+k':['s1:r1','s1:r2']}).delta.length,3);});
test('same command equivalent args with different property order is unchanged',()=>{const p=project([rule('a','same',{x:1,y:2}),rule('a','same',{y:2,x:1})],bools);assert.equal(analyzeProject(p,{'ctrl+k':['s1:r1','s1:r2']}).delta.length,0);});
test('absent args and explicit null args remain distinct',()=>{const p=project([rule('a'),rule('a','command',null)],bools);const r=analyzeProject(p,{'ctrl+k':['s1:r1','s1:r2']});assert.equal(r.delta.length,3);assert.equal(Object.hasOwn(r.exported[0],'args'),true);assert.equal(Object.hasOwn(r.exported[1],'args'),false);});
test('parse JSONC comments and trailing comma without touching string content',()=>{const parsed=parseSnippet('// first\n[{"key":"ctrl+k","command":"http://example/*data*/",},]');assert.equal(parsed[0].command,'http://example/*data*/');});
for(const text of ['{"a":1,"a":2}','{"nested":{"x":1,"x":2}}','[1,]','{"a":1,}','{"a":1}x','{"a":NaN}','{"a":1e999}','{"x":"\\ud800"}','{"x":"\\udc00"}','{"x":"\\ud800A"}','\u00a0{}','{"x":01}'])test(`strict JSON rejects ${JSON.stringify(text)}`,()=>assert.throws(()=>readJSON(text)));
for(const text of ['/* no end','[/*x*/1,,]','//only','[{"key":"a","key":"b"}]'])test(`JSONC rejects ${JSON.stringify(text)}`,()=>assert.throws(()=>parseSnippet(text)));
test('JSON supports own __proto__ as inert preserved argument data',()=>{const p=parseProject('{"version":1,"platform":"linux","model":{},"sources":[{"name":"safe","rules":[{"key":"k","command":"c","args":{"__proto__":{"polluted":true}}}]}]}');const r=analyzeProject(p);assert.equal({}.polluted,undefined);assert.equal(JSON.parse(makeArtifacts(r)['keybindings.json'])[0].args.__proto__.polluted,true);});
const exprCases=[['a || b && !a',{a:true,b:false},true],['!(a || b)',{},true],['a == false',{},true],['a != false',{},false],['a == true',{},false],['a != true',{},true],["lang == 'false'",{lang:'false'},true],["lang == 'hello world'",{lang:'hello world'},true],['lang != python',{},true],['lang == python',{},false],['true',{},true],['false',{},false],['!(!a)',{a:true},true]];
for(const [expr,ctx,want]of exprCases)test(`condition semantics: ${expr} ${JSON.stringify(ctx)}`,()=>{const ast=parseWhen(expr,model);assert.equal(evaluateWhen(ast,ctx),want);assert.equal(evaluateWhen(parseWhen(serializeWhen(ast),model),ctx),want);});
for(const expr of ['', '!!a','!a == true','lang == /python/','lang == not', 'a === true','a !== false','a =~ /x/','a in b','a not in b','a > 1','a < 2','a & b','a | b','a ? b : a','unknown','lang','a == python',"a == 'true'",'lang == false','lang == "python"',"lang == 'can\\'t'",'a &&','(a','a)','a b','a ==','a == true == true','/x/','a;alert(1)',"lang == 'newline\nvalue'"])test(`unsupported when is rejected: ${JSON.stringify(expr)}`,()=>assert.throws(()=>parseWhen(expr,model)));
for(const key of ['Ctrl+k','control+k','cmd+k','ctrl+k ctrl+c','ctrl++k','ctrl+ctrl+k','ctrl+[KeyK]','ctrl+;','ctrl+f20','ctrl+return','ctrl+esc','ctrl+option+k','alt+win+k'])test(`reject unsupported key ${key}`,()=>assert.throws(()=>validateKey(key,'linux')));
test('same-platform modifier order canonicalized without cross-platform guessing',()=>{assert.equal(validateKey('alt+ctrl+k','linux'),'ctrl+alt+k');assert.equal(validateKey('cmd+alt+k','mac'),'alt+cmd+k');assert.equal(validateKey('win+k','windows'),'win+k');});
for(const [label,mutate]of [
 ['version',p=>p.version=2],['platform',p=>p.platform='auto'],['unknown project field',p=>p.extra=true],['unknown source field',p=>p.sources[0].foo=true],['unknown rule field',p=>p.sources[0].rules[0].systemWide=true],['unknown model field',p=>p.model['whenfold.focus'].guess=true],['removal',p=>p.sources[0].rules[0].command='-demo.generic'],['empty command',p=>p.sources[0].rules[0].command=''],['command controls',p=>p.sources[0].rules[0].command='x\ny'],['empty source',p=>p.sources[0].rules=[]],['missing source',p=>p.sources=[]],['numeric model',p=>p.model['whenfold.focus']={type:'number',values:[0,1]}],['mismatched type',p=>p.model['whenfold.focus'].values=[true,'true']],['duplicate values',p=>p.model['whenfold.focus'].values=[true,true]],['empty values',p=>p.model['whenfold.focus'].values=[]],['constant key',p=>p.model.isLinux={type:'boolean',values:[true]}],['reserved key',p=>Object.defineProperty(p.model,'__proto__',{value:{type:'boolean',values:[true]},enumerable:true})],['lone surrogate',p=>p.sources[0].name='\udfff'],['100 rule limit',p=>p.sources[0].rules=Array.from({length:101},()=>rule('whenfold.focus'))],['4096 context limit',p=>{p.model={};for(let i=0;i<13;i++)p.model['b'+i]={type:'boolean',values:[false,true]};p.sources=[{name:'limit',rules:[rule('b1')]}];}]
])test(`project rejects ${label}`,()=>{const p=sample();mutate(p);assert.throws(()=>analyzeProject(p));});
for(const priority of [null,[],{'ctrl+q':[]},{'ctrl+alt+k':['s1:r1']},{'ctrl+alt+k':['s1:r1','s1:r1','s2:r1']},{'ctrl+alt+k':['s1:r1','s1:r2','s9:r9']}])test(`reject priority ${JSON.stringify(priority)}`,()=>assert.throws(()=>analyzeProject(sample(),priority)));
test('100 rules supported with one context and default fallback',()=>{const r=analyzeProject(project(Array.from({length:100},(_,i)=>rule(undefined,'c'+i))));assert.equal(r.stats.ruleCount,100);assert.equal(r.scenarios[0].after.command,'c99');assert.equal(r.stats.shadowedCount,99);});
test('4096 contexts supported at declared limit',()=>{const m={};for(let i=0;i<12;i++)m['b'+i]={type:'boolean',values:[false,true]};const r=analyzeProject(project([rule('b1')],m));assert.equal(r.stats.contextCount,4096);});
test('parenthesis depth is bounded',()=>assert.throws(()=>parseWhen('('.repeat(65)+'a'+')'.repeat(65),model)));
test('when length is bounded',()=>assert.throws(()=>parseWhen('a || '.repeat(500)+'b',model)));
test('JSON byte limit is enforced for UTF8',()=>assert.throws(()=>parseProject(JSON.stringify({x:'あ'.repeat(400000)}))));
test('JSON args are data; HTML escaping and CSV injection protection',()=>{const p=project([rule('a','<img src=x onerror=alert(1)>',{'x':'</script>'}),rule('a','=HYPERLINK("evil")',null)],bools);p.sources[0].name='<script>evil()</script>';const result=analyzeProject(p,{'ctrl+k':['s1:r1','s1:r2']});const artifacts=makeArtifacts(result);assert.ok(!artifacts['report.html'].includes('<script>evil'));assert.ok(artifacts['report.html'].includes('&lt;script&gt;evil'));assert.ok(artifacts['behavior-delta.csv'].includes("'=HYPERLINK"));assert.equal(JSON.parse(artifacts['keybindings.json'])[1].command,'<img src=x onerror=alert(1)>');});
test('repeated analysis/export is deterministic and does not mutate project',()=>{const p=sample(),original=JSON.stringify(p);const a=analyzeProject(p,chosen),b=analyzeProject(p,chosen);assert.deepEqual(makeArtifacts(a),makeArtifacts(b));assert.deepEqual(createZip(makeArtifacts(a)),createZip(makeArtifacts(b)));assert.equal(JSON.stringify(p),original);});
test('ZIP rejects traversal filenames',()=>assert.throws(()=>createZip({'../evil':'no'})));
test('source map covers all exports and identifies priorities',()=>{const r=analyzeProject(sample(),chosen);assert.equal(r.sourceMap.entries.length,3);for(const entry of r.sourceMap.entries){assert.equal(entry.guard,r.exported[entry.outputIndex].when);assert.equal(r.priority['ctrl+alt+k'][entry.priorityRank],entry.id);}});

test('bounded consumer normalization rejects compact exponential expressions',()=>{const m={a:{type:'boolean',values:[true,false]},b:{type:'boolean',values:[true,false]}};const expression=Array(14).fill('(a || b)').join(' && ');assert.throws(()=>analyzeProject(project([rule(expression)],m)),/normalization budget/);});

for(const command of ['^demo.foo','^','^-demo.foo'])test(`reject upstream bubbling prefix ${command}`,()=>assert.throws(()=>analyzeProject(project([rule(undefined,command)])),/bubbling/));

for(const whitespace of ['\v','\f','\u2003','\ufeff'])test(`reject whitespace outside pinned VS Code scanner ${JSON.stringify(whitespace)}`,()=>assert.throws(()=>parseWhen('a'+whitespace+'&& b',model),/Unsupported/));

for(const text of ['-0','-0.0','-0e4','-1e-9999','{"args":{"x":[-0]}}'])test(`reject JSON negative zero ${text}`,()=>assert.throws(()=>readJSON(text),/negative zero/));
test('programmatic nested negative-zero args cannot silently normalize',()=>assert.throws(()=>analyzeProject(project([rule(undefined,'demo.command',{nested:[-0]})])),/Negative zero/));
