/** Independent, deliberately bounded parser/compiler. Imported commands are data only. */
export const LIMITS = Object.freeze({ rules:100, contexts:4096, modelKeys:16, inputBytes:1048576, whenLength:2048, guardLength:32768, totalGuardLength:1048576, expressionDepth:64, scenarioBytes:16777216, dnfTerms:4096, dnfLiterals:65536 });
const own = (o,k)=>Object.prototype.hasOwnProperty.call(o,k);
const plain = x=>x!==null && typeof x==='object' && !Array.isArray(x) && (Object.getPrototypeOf(x)===Object.prototype || Object.getPrototypeOf(x)===null);
const fail = message=>{throw new Error(message)};
const bytes = s=>new TextEncoder().encode(s).length;
const badUnicode = s=>{for(let i=0;i<s.length;i++){const c=s.charCodeAt(i);if(c>=0xd800&&c<=0xdbff){const n=s.charCodeAt(++i);if(!(n>=0xdc00&&n<=0xdfff))return true;}else if(c>=0xdc00&&c<=0xdfff)return true;}return false;};
const checkText = (s,label,max=65536)=>{if(typeof s!=='string'||s.length>max||badUnicode(s))fail(`${label}: invalid, oversized, or malformed Unicode string`);return s;};
const objectFields = (o, allowed,label)=>{if(!plain(o))fail(`${label}: expected an object`);for(const key of Object.keys(o))if(!allowed.includes(key))fail(`${label}: unsupported field ${key}`);};
const cloneData = (x,depth=0)=>{if(depth>24)fail('JSON data exceeds depth 24');if(x===null||typeof x==='boolean')return x;if(typeof x==='number'){if(!Number.isFinite(x))fail('Non-finite JSON number');if(Object.is(x,-0))fail('Negative zero is unsupported because JSON export would normalize it');return x;}if(typeof x==='string')return checkText(x,'JSON string');if(Array.isArray(x))return x.map(y=>cloneData(y,depth+1));if(plain(x)){const out=Object.create(null);for(const [k,v]of Object.entries(x)){checkText(k,'JSON key');Object.defineProperty(out,k,{value:cloneData(v,depth+1),enumerable:true,writable:true,configurable:true});}return out;}fail('Only JSON values are supported');};
/** Strict JSON / JSONC reader rejects duplicate keys instead of silently losing intent. */
export function readJSON(text,comments=false){
 checkText(text,'Input',LIMITS.inputBytes);if(bytes(text)>LIMITS.inputBytes)fail('Input exceeds 1 MiB');let i=0;
 const error=m=>fail(`JSON at offset ${i}: ${m}`);
 function space(){for(;;){while(/[ \t\r\n]/.test(text[i]||'')&&i<text.length)i++;if(!comments||text[i]!=='/')return;if(text[i+1]==='/'){i+=2;while(i<text.length&&!/[\r\n]/.test(text[i]))i++;}else if(text[i+1]==='*'){const end=text.indexOf('*/',i+2);if(end<0)error('unterminated comment');i=end+2;}else return;}}
 function str(){const start=i++;while(i<text.length){if(text[i]==='\\'){i+=2;continue;}if(text[i++]==='"'){let s;try{s=JSON.parse(text.slice(start,i));}catch{error('invalid string');}checkText(s,'JSON string');return s;}}error('unterminated string');}
 function val(depth){if(depth>24)error('depth exceeds 24');space();const c=text[i];if(c==='"')return str();if(c==='{'||c==='['){i++;const arr=c==='[',out=arr?[]:Object.create(null),seen=new Set(),end=arr?']':'}';space();if(text[i]===end){i++;return out;}for(;;){space();let k;if(!arr){if(text[i]!=='"')error('expected quoted property');k=str();if(seen.has(k))error(`duplicate property ${k}`);seen.add(k);space();if(text[i++]!==':')error('expected colon');}const v=val(depth+1);if(arr)out.push(v);else Object.defineProperty(out,k,{value:v,enumerable:true,writable:true,configurable:true});space();if(text[i]===end){i++;return out;}if(text[i++]!==',')error('expected comma');space();if(text[i]===end){if(!comments)error('trailing comma');i++;return out;}}}
 for(const [s,v]of [['true',true],['false',false],['null',null]])if(text.slice(i,i+s.length)===s){i+=s.length;return v;}
 const m=text.slice(i).match(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?/);if(m){i+=m[0].length;const n=Number(m[0]);if(!Number.isFinite(n))error('non-finite number');if(Object.is(n,-0))error('negative zero is unsupported because JSON export would normalize it');return n;}error('expected JSON value');}
 const out=val(0);space();if(i!==text.length)error('unexpected trailing input');return out;
}
export const parseProject = text=>readJSON(text,false);
export function parseSnippet(text){const a=readJSON(text,true);if(!Array.isArray(a))fail('Snippet must be a JSON/JSONC array of ordered rules');if(a.length>LIMITS.rules)fail('At most 100 rules');return a;}
const RESERVED_CONTEXT_KEYS=new Set(['true','false','in','not','isMac','isLinux','isWindows','isWeb','isMacNative','isEdge','isFirefox','isChrome','isSafari','isIOS','isMobile','isDevelopment','isAndroid','isNative','__proto__','prototype','constructor']);
function validateModel(input){
 if(!plain(input))fail('model: expected an object');const names=Object.keys(input);if(names.length>LIMITS.modelKeys)fail('At most 16 context keys');let count=1;const model=Object.create(null);
 for(const name of names){if(!/^[A-Za-z_][A-Za-z0-9_.-]*$/.test(name)||RESERVED_CONTEXT_KEYS.has(name))fail(`Unsupported or reserved context key: ${name}`);const def=input[name];objectFields(def,['type','values'],`model.${name}`);if(!['boolean','string'].includes(def.type)||!Array.isArray(def.values)||!def.values.length||def.values.length>64)fail(`model.${name}: declare boolean/string and 1–64 values`);const seen=new Set();for(const value of def.values){if(value!==null&&typeof value!==def.type)fail(`model.${name}: wrong value type; null means absent`);if(typeof value==='string')checkText(value,`model.${name}`,256);const token=JSON.stringify(value);if(seen.has(token))fail(`model.${name}: duplicate value`);seen.add(token);}count*=def.values.length;if(count>LIMITS.contexts)fail('Context model exceeds 4096 combinations');model[name]={type:def.type,values:[...def.values]};}return model;
}
export function enumerateContexts(model){let contexts=[{}];for(const [key,{values}]of Object.entries(model)){const next=[];for(const c of contexts)for(const value of values){const copy={...c};if(value!==null)copy[key]=value;next.push(copy);}contexts=next;}return contexts;}
/** Tokens follow a conservative subset of VS Code expressions; no JS evaluation. */
export function parseWhen(text,model){
 if(text===undefined)return {op:'const',value:true};checkText(text,'when',LIMITS.whenLength);if(!text.trim())fail('Empty when clause is unsupported; omit when for unconditional rules');const tokens=[];let i=0;
 while(i<text.length){if(/[ \t\r\n\u00a0]/.test(text[i])){i++;continue;}const pair=text.slice(i,i+2);if(['&&','||','==','!='].includes(pair)){tokens.push({type:pair});i+=2;continue;}if('!()'.includes(text[i])){tokens.push({type:text[i++]});continue;}if(text[i]==="'"){const start=++i;while(i<text.length&&text[i]!=="'"){if(text[i]==='\\'||/[\r\n\x00-\x1f]/.test(text[i]))fail('Escapes/control characters in when literals are unsupported');i++;}if(i===text.length)fail('Unterminated single-quoted when literal');tokens.push({type:'literal',value:text.slice(start,i++),quoted:true});continue;}const m=text.slice(i).match(/^[A-Za-z0-9_.:\/-]+/);if(m){tokens.push({type:'word',value:m[0]});i+=m[0].length;continue;}fail(`Unsupported when syntax at offset ${i}`);}
 let t=0;const peek=()=>tokens[t]?.type;const take=type=>{if(peek()!==type)fail(`Expected ${type} in when clause`);return tokens[t++];};
 function atom(depth){if(depth>LIMITS.expressionDepth)fail('when nesting exceeds 64');if(peek()==='!'){t++;if(peek()==='(')return {op:'not',child:atom(depth+1)};const neg=take('word'),name=neg.value;if(name==='true'||name==='false')return {op:'const',value:name!=='true'};if(!own(model,name)||model[name].type!=='boolean')fail('Negation requires a declared boolean key or parentheses');return {op:'not',child:{op:'key',key:name}};}if(peek()==='('){t++;const x=or(depth+1);take(')');return x;}const token=take('word'),key=token.value;if(key==='true'||key==='false')return {op:'const',value:key==='true'};if(!own(model,key))fail(`Undeclared context key: ${key}`);if(peek()==='=='||peek()==='!='){const op=tokens[t++].type;const rhs=tokens[t++];if(!rhs||!['word','literal'].includes(rhs.type))fail('Equality needs a string/boolean literal');if(!rhs.quoted&&(rhs.value==='not'||rhs.value.startsWith('/')))fail('Quote this equality value; unquoted not/regex-like values are unsupported');if(model[key].type==='boolean'){if(rhs.quoted||!['true','false'].includes(rhs.value))fail(`Boolean context ${key} requires unquoted true/false equality`);const positive=(rhs.value==='true')===(op==='==');return positive?{op:'key',key}:{op:'not',child:{op:'key',key}};}if(!rhs.quoted&&['true','false'].includes(rhs.value))fail(`String context ${key}: quote true/false string values`);return {op:op==='=='?'eq':'ne',key,value:rhs.value};}if(model[key].type!=='boolean')fail(`String context ${key} requires == or !=`);return {op:'key',key};}
 function and(depth){let x=atom(depth);while(peek()==='&&'){t++;x={op:'and',left:x,right:atom(depth)};}return x;}
 function or(depth){let x=and(depth);while(peek()==='||'){t++;x={op:'or',left:x,right:and(depth)};}return x;}
 const out=or(0);if(t!==tokens.length)fail('Unsupported operator or trailing when tokens');return out;
}
export function evaluateWhen(ast,context){switch(ast.op){case'const':return ast.value;case'key':return context[ast.key]===true;case'eq':return context[ast.key]===ast.value;case'ne':return context[ast.key]!==ast.value;case'not':return !evaluateWhen(ast.child,context);case'and':return evaluateWhen(ast.left,context)&&evaluateWhen(ast.right,context);case'or':return evaluateWhen(ast.left,context)||evaluateWhen(ast.right,context);default:fail('Unknown expression node');}}
export function serializeWhen(ast){switch(ast.op){case'const':return ast.value?'true':'false';case'key':return ast.key;case'eq':case'ne':return `${ast.key} ${ast.op==='eq'?'==':'!='} '${ast.value}'`;case'not':return `!(${serializeWhen(ast.child)})`;case'and':case'or':return `(${serializeWhen(ast.left)} ${ast.op==='and'?'&&':'||'} ${serializeWhen(ast.right)})`;default:fail('Unknown expression node');}}
// VS Code normalizes conjunctions/disjunctions. Bound a conservative DNF expansion
// before exporting, so a short alternating expression cannot explode in its parser.
export function checkExpansion(ast){
 function count(x,neg=false){if(x.op==='const')return [x.value!==neg?1:0,0];if(x.op==='not')return count(x.child,!neg);if(!['and','or'].includes(x.op))return [1,1];const a=count(x.left,neg),b=count(x.right,neg),and=(x.op==='and')!==neg;const terms=and?a[0]*b[0]:a[0]+b[0],literals=and?a[1]*b[0]+b[1]*a[0]:a[1]+b[1];if(terms>LIMITS.dnfTerms||literals>LIMITS.dnfLiterals)fail('Expression/guard normalization budget exceeded (4096 DNF terms / 65536 literals); simplify conditions or split the group');return [terms,literals];}
 return count(ast);
}
function not(x){if(x.op==='const')return {op:'const',value:!x.value};if(x.op==='not')return x.child;return{op:'not',child:x};}
function combine(op,a,b){if(a.op==='const'){if(op==='and')return a.value?b:a;return a.value?a:b;}if(b.op==='const'){if(op==='and')return b.value?a:b;return b.value?b:a;}if(serializeWhen(a)===serializeWhen(b))return a;return{op,left:a,right:b};}
const BASE_KEYS=new Set([...Array.from({length:26},(_,i)=>String.fromCharCode(97+i)),...Array.from({length:10},(_,i)=>String(i)),...Array.from({length:19},(_,i)=>`f${i+1}`),'left','up','right','down','pageup','pagedown','end','home','tab','enter','escape','space','backspace','delete','insert','pausebreak','capslock']);
export function validateKey(key,platform){checkText(key,'key',100);if(!key||/\s/.test(key)||key!==key.toLowerCase())fail('Use lowercase canonical single-stroke key syntax; chords/aliases/case conversion are unsupported');const parts=key.split('+'),base=parts.pop(),allowed=['ctrl','shift','alt',...(platform==='mac'?['cmd']:platform==='windows'?['win']:['meta'])];if(!BASE_KEYS.has(base))fail(`Unsupported base key: ${base}`);const seen=new Set();for(const mod of parts){if(!allowed.includes(mod)||seen.has(mod))fail(`Unsupported or repeated modifier: ${mod}`);seen.add(mod);}const canonical=allowed.filter(m=>seen.has(m));return [...canonical,base].join('+');}
function validateProject(project){
 objectFields(project,['version','platform','sources','model'],'Project');if(project.version!==1)fail('Project version must be 1');if(!['linux','windows','mac'].includes(project.platform))fail('Choose explicit platform: linux, windows, or mac');if(!Array.isArray(project.sources)||!project.sources.length||project.sources.length>100)fail('Provide 1–100 ordered sources');cloneData(project);if(bytes(JSON.stringify(project))>LIMITS.inputBytes)fail('Project exceeds 1 MiB');const model=validateModel(project.model),rules=[];
 project.sources.forEach((source,si)=>{objectFields(source,['name','rules'],`Source ${si+1}`);checkText(source.name,'Source name',100);if(!source.name.trim())fail('Source name cannot be empty');if(!Array.isArray(source.rules)||!source.rules.length)fail('Each source needs at least one rule');source.rules.forEach((input,ri)=>{if(rules.length>=LIMITS.rules)fail('At most 100 rules');objectFields(input,['key','command','when','args'],`Rule ${si+1}:${ri+1}`);const key=validateKey(input.key,project.platform);checkText(input.command,'command',256);if(!input.command.trim()||input.command.startsWith('-')||input.command.startsWith('^')||/[\x00-\x1f]/.test(input.command))fail('Empty/suppression/removal/bubbling or control-character command IDs are unsupported');const ast=parseWhen(input.when,model);checkExpansion(ast);const rule={id:`s${si+1}:r${ri+1}`,source:source.name,sourceIndex:si,index:ri,key,command:input.command,when:input.when??'true'};if(own(input,'args'))rule.args=cloneData(input.args);Object.defineProperty(rule,'ast',{value:ast,enumerable:false});rules.push(rule);});});return {model,rules};
}
function outcome(rule){if(!rule)return null;const o={id:rule.id,command:rule.command};if(own(rule,'args'))o.args=cloneData(rule.args);return o;}
function canonicalData(x){if(Array.isArray(x))return '['+x.map(canonicalData).join(',')+']';if(plain(x))return '{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonicalData(x[k])).join(',')+'}';return JSON.stringify(x);}
function behaviorEqual(a,b){if(a===null||b===null)return a===b;return a.command===b.command&&own(a,'args')===own(b,'args')&&canonicalData(a.args)===canonicalData(b.args);}
export function analyzeProject(project,requestedPriority={}){
 const {model,rules}=validateProject(project);if(!plain(requestedPriority))fail('Priority must be a shortcut-to-rule-ID object');const contexts=enumerateContexts(model),byId=new Map(rules.map(r=>[r.id,r])),groupMap=new Map();for(const rule of rules){if(!groupMap.has(rule.key))groupMap.set(rule.key,[]);groupMap.get(rule.key).push(rule.id);}for(const key of Object.keys(requestedPriority))if(!groupMap.has(key))fail(`Priority contains unknown shortcut: ${key}`);
 const priority=Object.create(null),groups=[];for(const [key,ids]of groupMap){const choice=own(requestedPriority,key)?requestedPriority[key]:[...ids].reverse();if(!Array.isArray(choice)||choice.length!==ids.length||new Set(choice).size!==ids.length||choice.some(id=>!ids.includes(id)))fail(`Priority for ${key} must include each group rule exactly once`);priority[key]=[...choice];groups.push({key,ruleIds:[...ids],priority:[...choice]});}
 const exported=[],entries=[],compiled=new Map();let totalGuards=0;for(const group of groups){let higher={op:'const',value:false};const guarded=[];for(const [rank,id]of priority[group.key].entries()){const rule=byId.get(id),guard=combine('and',rule.ast,not(higher));checkExpansion(guard);const when=serializeWhen(guard);if(when.length>LIMITS.guardLength)fail('Generated guard exceeds 32768 characters; split the shortcut group');totalGuards+=when.length;if(totalGuards>LIMITS.totalGuardLength)fail('Generated guards exceed 1 MiB');const output={key:rule.key,command:rule.command,when};if(own(rule,'args'))output.args=cloneData(rule.args);compiled.set(id,guard);guarded.push({rule,output,rank});higher=combine('or',higher,rule.ast);}for(const {rule,output,rank}of guarded.reverse()){const outputIndex=exported.length;exported.push(output);entries.push({outputIndex,id:rule.id,source:rule.source,sourceIndex:rule.sourceIndex,ruleIndex:rule.index,originalWhen:rule.when,guard:output.when,priorityRank:rank});}}
 let scenarioBytes=0;const scenarios=[],delta=[],overlaps=[],wins=new Set(),matches=new Map(rules.map(r=>[r.id,contexts.map(c=>evaluateWhen(r.ast,c))]));for(const group of groups){for(let ci=0;ci<contexts.length;ci++){const context=contexts[ci],original=[...group.ruleIds].reverse().find(id=>matches.get(id)[ci]),chosen=priority[group.key].find(id=>matches.get(id)[ci]),matchedExportIds=group.ruleIds.filter(id=>evaluateWhen(compiled.get(id),context));if(matchedExportIds.length>1||matchedExportIds[0]!==chosen)fail('Internal compiler invariant failed');if(chosen)wins.add(chosen);const scenario={context,key:group.key,before:outcome(byId.get(original)),after:outcome(byId.get(chosen)),matchedExportIds};scenarioBytes+=bytes(JSON.stringify(scenario));if(scenarioBytes>LIMITS.scenarioBytes)fail('Scenario export exceeds 16 MiB; reduce context combinations, shortcut groups, or args');scenarios.push(scenario);if(!behaviorEqual(scenario.before,scenario.after))delta.push(scenario);}for(let a=0;a<group.ruleIds.length;a++)for(let b=a+1;b<group.ruleIds.length;b++){const aid=group.ruleIds[a],bid=group.ruleIds[b];let count=0,first=-1;for(let ci=0;ci<contexts.length;ci++)if(matches.get(aid)[ci]&&matches.get(bid)[ci]){count++;if(first<0)first=ci;}if(count){const witness=contexts[first];overlaps.push({key:group.key,ruleIds:[aid,bid],count,witness,originalWinner:outcome(byId.get([...group.ruleIds].reverse().find(id=>matches.get(id)[first]))),chosenWinner:outcome(byId.get(priority[group.key].find(id=>matches.get(id)[first])))});}}}
 const coverage={rules:'Only supplied ordered rules; unknown built-in/extension rules are not covered',contexts:'Logical combinations in the declared finite model, not proof of editor reachability',platform:project.platform,syntax:'Single stroke; ! && || () == !=; typed boolean/string keys; null means absent',format:'Source comments and formatting are not preserved'};
 return {version:1,platform:project.platform,model,contexts,rules,groups,overlaps,exported,sourceMap:{version:1,platform:project.platform,entries,coverage},scenarios,delta,stats:{contextCount:contexts.length,ruleCount:rules.length,groupCount:groups.length,overlapCount:overlaps.length,changedCount:delta.length,shadowedCount:rules.length-wins.size},priority,coverage};
}
